language:  ruby
sudo: required
dist: trusty
cache: bundler
rvm:
    - 2.3.1
addons:
  firefox: 47.0.1
before_install:
  - mkdir -p ~/drivers; export PATH=~/drivers:$PATH;
  - GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz";
    FILE=`mktemp`; wget "$GECKODRIVER_URL" -qO $FILE && tar xz -C ~/drivers -f $FILE geckodriver; rm $FILE; chmod 777 ~/drivers/geckodriver;
    ~/drivers/geckodriver --version;
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script:
    bundle exec rake features
